services:
  hutaobot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hutaobot
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: production
      TZ: America/Sao_Paulo
    volumes:
      - ./assets/qr-code:/app/assets/qr-code
      - ./assets/users:/app/assets/users
      - ./assets/settings:/app/assets/settings
    command: npm start
